# Generated by Django 3.0.5 on 2020-10-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
